---
- name: Configuration of Aplication Server
  hosts: app1
  become: true
  vars:
    dbhost: db1
    dbname: notes
    dbusername: root
    dbpassword: admin
  tasks:
    - name: Configure hosts in ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: '{{item}}'
      with_items:
          - 192.168.1.2 control-node
          - 192.168.1.3 app1
          - 192.168.1.4 db1
    - name: Add users
      user:
        name: app
        comment: Application user
        uid: 500
    - name: Download Maven
      get_url:
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.1.0/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/apache-maven-3.1.0-bin.tar.gz
    - name: Unzip Maven Package
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/
        remote_src: yes
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: Creation off directory app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: Git client installation
      yum:
        name: git
        state: latest
    - name: Repository Clone api
      git: 
        repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: /opt/notes
        clone: yes
        force: yes
    - name: Configure pom.xml archive
      template:
        src: pom.xml
        dest: /opt/notes/pom.xml
    - name: Archives of properties to db
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: Generate application package
      command: /opt/apache-maven-3.1.0/bin/mvn -f /opt/notes/pom.xml package 
      become_user: app
    - name: Register current version in package
      shell:
        cmd: /opt/apache-maven-3.1.0/bin/mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['
        chdir: /opt/notes/
      register: app_version
    - name: Configuration of Systemd service
      template:
        src: etc/systemd/system/notes.service
        dest: /etc/systemd/system/notes.service
        owner: root
        group: root
        mode: '0600'
      notify: reload daemon
    - name: Start Service notes
      service:
        name: notes
        state: restarted
  roles:
    - default-so-configuration
  handlers:
    - name: reload app 
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes