---
- name: 'Configuration of Database'
  hosts: db1
  user: 'vagrant'
  become: true
  vars_files:
    - vars/main.yml
  vars:
    dbname: 'notes'
    dbusername: 'root'
    dbpassword: 'admin'
  tasks:
    - name: 'Configure hosts in ansible'
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app1
        - 192.168.1.4 db1
  roles:
    - default-so-configuration
    - role: geerlingguy.mysql
 